import { useState } from "react";
import { fetchGenerateNotes } from "../services/api";
import { toast } from "react-toastify";
import { jsPDF } from "jspdf";

function NotesGeneratorCard() {
    const [topic, setTopic] = useState("");
    const [notes, setNotes] = useState(null);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState("");
    const [history, setHistory] = useState([]);

    const handleGenerate = async () => {
        if (!topic.trim()) { toast.error("❌ Please enter a topic."); return; }
        if (topic.trim().length < 2) { toast.error("❌ Topic must be at least 2 characters."); return; }
        if (topic.trim().length > 100) { toast.error("❌ Topic must be under 100 characters."); return; }
        try {
            setLoading(true);
            setError("");
            setNotes(null);
            const data = await fetchGenerateNotes(topic, () =>
                toast.info("⏳ Backend is waking up, please wait...", { autoClose: 10000 })
            );
            if (data.error) {
                setError(`❌ ${data.error}`);
                toast.error("Could not generate notes. Please try again.");
            } else {
                setNotes(data);
                setHistory((prev) => [topic, ...prev.slice(0, 4)]);
                toast.success(`Notes for ${data.topic} ready!`);
            }
        } catch {
            setError("⚠️ Something went wrong. Please try again in a moment.");
            toast.error("Could not generate notes. Please try again.");
        } finally {
            setLoading(false);
        }
    };

    const clearAll = () => {
        setTopic("");
        setNotes(null);
        setError("");
    };

    const downloadNotes = () => {
        const pdf = new jsPDF();
        pdf.setFontSize(18);
        pdf.setTextColor(79, 70, 229);
        pdf.text("Smart Study AI — Study Notes", 20, 20);
        pdf.setFontSize(10);
        pdf.setTextColor(107, 114, 128);
        pdf.text(`Generated on ${new Date().toLocaleDateString()}`, 20, 30);
        pdf.setDrawColor(226, 232, 240);
        pdf.line(20, 34, 190, 34);

        pdf.setFontSize(16);
        pdf.setTextColor(30, 27, 75);
        pdf.text(notes.topic.toUpperCase(), 20, 48);

        let y = 58;
        if (notes.summary) {
            pdf.setFontSize(11);
            pdf.setTextColor(55, 65, 81);
            const summaryLines = pdf.splitTextToSize(notes.summary, 165);
            pdf.text(summaryLines, 20, y);
            y += summaryLines.length * 6 + 8;
        }

        (notes.sections || []).forEach((section) => {
            if (y > 260) { pdf.addPage(); y = 20; }
            pdf.setFontSize(13);
            pdf.setTextColor(79, 70, 229);
            pdf.text(section.heading, 20, y);
            y += 8;
            (section.points || []).forEach((point) => {
                if (y > 270) { pdf.addPage(); y = 20; }
                pdf.setFontSize(10);
                pdf.setTextColor(55, 65, 81);
                const lines = pdf.splitTextToSize(`• ${point}`, 160);
                pdf.text(lines, 25, y);
                y += lines.length * 6 + 2;
            });
            y += 4;
        });

        if (notes.key_terms?.length) {
            if (y > 240) { pdf.addPage(); y = 20; }
            pdf.setFontSize(13);
            pdf.setTextColor(79, 70, 229);
            pdf.text("Key Terms", 20, y);
            y += 8;
            notes.key_terms.forEach((term) => {
                if (y > 270) { pdf.addPage(); y = 20; }
                pdf.setFontSize(10);
                pdf.setTextColor(55, 65, 81);
                const lines = pdf.splitTextToSize(`• ${term}`, 160);
                pdf.text(lines, 25, y);
                y += lines.length * 6 + 2;
            });
        }

        if (notes.quick_facts?.length) {
            if (y > 240) { pdf.addPage(); y = 20; }
            pdf.setFontSize(13);
            pdf.setTextColor(79, 70, 229);
            pdf.text("Quick Facts", 20, y);
            y += 8;
            notes.quick_facts.forEach((fact) => {
                if (y > 270) { pdf.addPage(); y = 20; }
                pdf.setFontSize(10);
                pdf.setTextColor(55, 65, 81);
                const lines = pdf.splitTextToSize(`• ${fact}`, 160);
                pdf.text(lines, 25, y);
                y += lines.length * 6 + 2;
            });
        }

        pdf.setFontSize(9);
        pdf.setTextColor(156, 163, 175);
        pdf.text("Generated by Smart Study AI — smart-study-ai-five.vercel.app", 20, 285);

        pdf.save(`SmartStudyAI_${notes.topic}_Notes.pdf`);
        toast.success("Notes downloaded as PDF!");
    };

    return (
        <div className="card">
            <h2>📝 AI Notes Generator</h2>
            <p style={{ color: "var(--text-secondary)", fontSize: "14px", marginTop: "-8px" }}>
                Enter any topic to generate structured study notes instantly
            </p>
            <input
                type="text"
                placeholder="Enter topic (e.g. photosynthesis, binary trees, world war 2)"
                value={topic}
                onChange={(e) => setTopic(e.target.value)}
                onKeyDown={(e) => { if (e.key === "Enter") handleGenerate(); }}
            />
            <div className="button-row">
                <button onClick={handleGenerate} disabled={loading}>
                    {loading ? "⏳ Generating..." : "Generate Notes"}
                </button>
                <button className="btn-clear" onClick={clearAll}>Clear</button>
            </div>

            {error && <p className="error">{error}</p>}

            {notes && (
                <div className="result-box">
                    <h3>{notes.topic.toUpperCase()}</h3>
                    {notes.summary && (
                        <p style={{ color: "var(--text-secondary)", lineHeight: 1.7, marginBottom: "16px" }}>
                            {notes.summary}
                        </p>
                    )}

                    {(notes.sections || []).map((section, index) => (
                        <div key={index} style={{ marginBottom: "16px" }}>
                            <h4 style={{ color: "var(--accent)", marginBottom: "8px", fontSize: "15px" }}>
                                {section.heading}
                            </h4>
                            <ul className="task-list">
                                {(section.points || []).map((point, i) => (
                                    <li key={i}><span>{point}</span></li>
                                ))}
                            </ul>
                        </div>
                    ))}

                    {notes.key_terms?.length > 0 && (
                        <div style={{ marginBottom: "16px" }}>
                            <h4 style={{ color: "var(--accent)", marginBottom: "8px", fontSize: "15px" }}>
                                📖 Key Terms
                            </h4>
                            <ul className="task-list">
                                {notes.key_terms.map((term, i) => (
                                    <li key={i}><span>{term}</span></li>
                                ))}
                            </ul>
                        </div>
                    )}

                    {notes.quick_facts?.length > 0 && (
                        <div style={{ marginBottom: "16px" }}>
                            <h4 style={{ color: "var(--accent)", marginBottom: "8px", fontSize: "15px" }}>
                                ⚡ Quick Facts
                            </h4>
                            <ul className="task-list">
                                {notes.quick_facts.map((fact, i) => (
                                    <li key={i}><span>{fact}</span></li>
                                ))}
                            </ul>
                        </div>
                    )}

                    <div style={{ display: "flex", gap: "10px", marginTop: "4px" }}>
                        <button onClick={downloadNotes} style={{ background: "linear-gradient(135deg, #6366f1, #8b5cf6)", flex: 1 }}>
                            ⬇️ Download Notes as PDF
                        </button>
                        <button
                            onClick={() => {
                                const text = `${notes.topic.toUpperCase()}\n\n${notes.summary}\n\n${notes.sections.map(s => `${s.heading}\n${s.points.map(p => `• ${p}`).join("\n")}`).join("\n\n")}\n\nKey Terms:\n${notes.key_terms?.join("\n")}\n\nQuick Facts:\n${notes.quick_facts?.join("\n")}`;
                                navigator.clipboard.writeText(text);
                                toast.success("📋 Notes copied!");
                            }}
                            style={{ background: "var(--glass-bg)", color: "var(--text-secondary)", border: "1px solid var(--glass-border)", boxShadow: "none", padding: "10px 16px" }}
                        >
                            📋 Copy
                        </button>
                    </div>
                </div>
            )}

            {history.length > 0 && (
                <div className="history-box">
                    <h4>🕘 Recent Topics</h4>
                    <ul>
                        {history.map((item, index) => (
                            <li key={index} onClick={() => setTopic(item)} title="Click to reuse">
                                {item}
                            </li>
                        ))}
                    </ul>
                </div>
            )}
        </div>
    );
}

export default NotesGeneratorCard;
