import { useState } from "react";
import { fetchStudyPlan, saveStudyPlan } from "../services/api";
import { toast } from "react-toastify";
import { jsPDF } from "jspdf";

function StudyPlanCard() {
    const [topic, setTopic] = useState("");
    const [studyPlan, setStudyPlan] = useState(null);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState("");
    const [history, setHistory] = useState([]);

    const handleStudy = async () => {
        if (!topic.trim()) return;
        try {
            setLoading(true);
            setError("");
            const data = await fetchStudyPlan(topic);
            setStudyPlan(data);
            toast.success(`Study plan for ${data.topic} ready!`);
            setHistory((prev) => [topic, ...prev]);
            try {
                await saveStudyPlan(data.topic, data.difficulty, JSON.stringify(data.tasks));
            } catch {
                // silent fail
            }
        } catch {
            setError("⚠️ Could not connect to backend. Is FastAPI running?");
            toast.error("Could not generate study plan.");
        } finally {
            setLoading(false);
        }
    };

    const clearAll = () => {
        setTopic("");
        setStudyPlan(null);
        setError("");
        setHistory([]);
    };
    const downloadStudyPlan = () => {
        const pdf = new jsPDF();
        pdf.setFontSize(18);
        pdf.setTextColor(79, 70, 229);
        pdf.text("Smart Study AI — Study Plan", 20, 20);
        pdf.setFontSize(10);
        pdf.setTextColor(107, 114, 128);
        pdf.text(`Generated on ${new Date().toLocaleDateString()}`, 20, 30);
        pdf.setDrawColor(226, 232, 240);
        pdf.line(20, 34, 190, 34);
    
        pdf.setFontSize(16);
        pdf.setTextColor(30, 27, 75);
        pdf.text(studyPlan.topic.toUpperCase(), 20, 48);
    
        pdf.setFontSize(11);
        pdf.setTextColor(79, 70, 229);
        pdf.text(`Difficulty: ${studyPlan.difficulty}`, 20, 58);
    
        pdf.setFontSize(12);
        pdf.setTextColor(30, 27, 75);
        pdf.text("Tasks:", 20, 72);
    
        let y = 82;
        studyPlan.tasks.forEach((task, i) => {
            pdf.setFontSize(10);
            pdf.setTextColor(55, 65, 81);
            const lines = pdf.splitTextToSize(`${i + 1}. ${task}`, 165);
            pdf.text(lines, 25, y);
            y += lines.length * 7 + 2;
        });
    
        pdf.setFontSize(9);
        pdf.setTextColor(156, 163, 175);
        pdf.text("Generated by Smart Study AI — smart-study-ai-five.vercel.app", 20, 280);
    
        pdf.save(`SmartStudyAI_${studyPlan.topic}_Plan.pdf`);
        toast.success("Study plan downloaded as PDF!");
    };

    return (
        <div className="card">
            <h2>📚 Get Study Plan</h2>
            <input
                type="text"
                placeholder="Enter topic (e.g. react, dbms, ai)"
                value={topic}
                onChange={(e) => setTopic(e.target.value)}
                onKeyDown={(e) => { if (e.key === "Enter") handleStudy(); }}
            />
            <div className="button-row">
                <button onClick={handleStudy} disabled={loading}>
                    {loading ? "Loading..." : "Get Plan"}
                </button>
                <button className="btn-clear" onClick={clearAll}>Clear</button>
            </div>

            {error && <p className="error">{error}</p>}

            {studyPlan && (
                <div className="result-box">
                    <h3>{studyPlan.topic.toUpperCase()}</h3>
                    <p className="difficulty">Difficulty: <strong>{studyPlan.difficulty}</strong></p>
                    <ul className="task-list">
                        {studyPlan.tasks.map((task, index) => (
                            <li key={index}>
                                <input type="checkbox" />
                                <span>{task}</span>
                            </li>
                        ))}
                    </ul>
                    <div style={{marginTop: "12px"}}>
                        <button
                            onClick={downloadStudyPlan}
                            style={{background: "#10b981", color: "white", border: "none", borderRadius: "8px", padding: "8px 16px", cursor: "pointer", fontSize: "14px"}}
                        >
                            ⬇️ Download Study Plan PDF
                        </button>
                    </div>
                </div>
            )}

            {history.length > 0 && (
                <div className="history-box">
                    <h4>🕘 Recent Topics</h4>
                    <ul>
                        {history.map((item, index) => (
                            <li key={index}>{item}</li>
                        ))}
                    </ul>
                </div>
            )}
        </div>
    );
}

export default StudyPlanCard;